# Generated by Django 5.2.2 on 2025-06-05 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('color', models.CharField(max_length=50)),
                ('wb_id', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
