# Generated by Django 5.2.2 on 2025-06-06 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ColorVariant',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('color_code', models.CharField(blank=True, max_length=20, null=True)),
                ('color_name', models.CharField(blank=True, max_length=20, null=True)),
                ('pics', models.IntegerField()),
                ('total_quantity', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='products.card')),
            ],
        ),
        migrations.CreateModel(
            name='ProductItem',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('size_name', models.CharField(max_length=50)),
                ('orig_name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('color_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.colorvariant')),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
