# Generated by Django 5.2.2 on 2025-06-06 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_card_colorvariant_productitem_delete_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='productitem',
            name='optionId',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productitem',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
