# Generated by Django 5.2.2 on 2025-06-06 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productitem_optionid_alter_productitem_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productitem',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
