# Generated by Django 5.2.2 on 2025-06-06 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_productitem_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='colorvariant',
            name='img_main',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
