# Generated by Django 5.2.2 on 2025-06-08 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_colorvariant_in_stock_productitem_in_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productitem',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
