# Generated by Django 5.2.2 on 2025-06-08 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_productitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='colorvariant',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
