# Generated by Django 5.2.2 on 2025-06-08 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_colorvariant_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('color_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Colors',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('color_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='colorvariant',
            name='color_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='colorvariant',
            name='color_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
