# Generated by Django 5.2.2 on 2025-06-08 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_brands_colors_alter_colorvariant_color_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='colors',
            old_name='color_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='brands',
            name='color_name',
        ),
        migrations.AddField(
            model_name='brands',
            name='brand',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
