# Generated by Django 5.2.2 on 2025-06-08 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_rename_color_name_colors_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Brands',
            new_name='Brand',
        ),
        migrations.RenameModel(
            old_name='Colors',
            new_name='Color',
        ),
        migrations.RemoveField(
            model_name='colorvariant',
            name='color_code',
        ),
        migrations.RemoveField(
            model_name='colorvariant',
            name='color_name',
        ),
        migrations.AddField(
            model_name='colorvariant',
            name='colors',
            field=models.ManyToManyField(related_name='colors', to='products.color'),
        ),
        migrations.AlterField(
            model_name='colorvariant',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color_variants', to='products.card'),
        ),
    ]
