# Generated by Django 5.2.2 on 2025-06-08 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_rename_brands_brand_rename_colors_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productitem',
            name='color_variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='products.colorvariant'),
        ),
    ]
