# Generated by Django 5.2.2 on 2025-06-08 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_productitem_color_variant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kind',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='colorvariant',
            name='kinds',
            field=models.ManyToManyField(blank=True, related_name='kinds', to='products.kind'),
        ),
    ]
