# Generated by Django 5.2.2 on 2025-06-08 17:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_kind_colorvariant_kinds'),
    ]

    operations = [
        migrations.AddField(
            model_name='kind',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='kind',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
