# Generated by Django 5.2.2 on 2025-06-08 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_kind_id_alter_kind_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kind',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
