# Generated by Django 5.2.2 on 2025-06-08 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_alter_kind_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='colorvariant',
            name='desc',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='colorvariant',
            name='grouped_options',
            field=models.TextField(blank=True),
        ),
    ]
